spring:
  cloud:
    config:
      import-check:
        enabled: false
  service:
    base-url: https://jsonplaceholder.typicode.com

server:
  port: 8090
  servlet:
    context-path: /user-mng-srv

